#!/usr/bin/env bash
# Life Ops — Calendar Brief
# Reads calendar and reports today's events and meeting load
# Runs: weekdays at 6 AM

set -euo pipefail

DATA_DIR="${HOME}/.hermes/agentlife/data"
mkdir -p "$DATA_DIR"

BRIEF_FILE="${DATA_DIR}/calendar-$(date +%Y-%m-%d).md"

cat > "$BRIEF_FILE" << EOF
# 📅 Calendar Brief
## $(date "+%A, %B %d, %Y")

**Meeting Load:** N/A (configure calendar integration)

### Events
| Time | Event | Duration |
|------|-------|----------|
| — | — | — |

### Focus Time
| Block | Duration |
|-------|----------|
| — | — |

---
_Generated by AgentLife Life Ops_
EOF

echo "Calendar brief: $BRIEF_FILE"
cat "$BRIEF_FILE"