#!/usr/bin/env bash
# Life Ops — Daily Brief
# Combines portfolio, spending, calendar, and subscription data
# Runs: weekdays at 6:30 AM
# Output: markdown brief delivered to configured channel

set -euo pipefail

BRIEF_DIR="${HOME}/.hermes/agentlife/daily-brief"
mkdir -p "$BRIEF_DIR"

DATE=$(date "+%A, %B %d")
BRIEF_FILE="${BRIEF_DIR}/$(date +%Y-%m-%d).md"

cat > "$BRIEF_FILE" << EOF
# Good morning.

**${DATE}**

EOF

# ── SECTION: Portfolio if available ─────────────────────────────
if [ -f "${BRIEF_DIR}/../data/net-worth.json" ]; then
  NW=$(python3 -c "
import json
with open('${BRIEF_DIR}/../data/net-worth.json') as f:
    d = json.load(f)
print(d.get('total', 'N/A'))
  " 2>/dev/null || echo "N/A")
  echo "## 📊 Net Worth: \$${NW}" >> "$BRIEF_FILE"
else
  echo "## 📊 Net Worth: configure portfolio tracking to populate" >> "$BRIEF_FILE"
fi

# ── SECTION: Today's Calendar ───────────────────────────────────
echo "" >> "$BRIEF_FILE"
echo "## 📅 Today" >> "$BRIEF_FILE"
echo "- _(calendar brief: configure calendar integration)_" >> "$BRIEF_FILE"

# ── SECTION: Upcoming Renewals ──────────────────────────────────
echo "" >> "$BRIEF_FILE"
echo "## 🔔 Renewals" >> "$BRIEF_FILE"
echo "- _(subscription tracking: configure bill management)_" >> "$BRIEF_FILE"

echo "" >> "$BRIEF_FILE"
echo "---" >> "$BRIEF_FILE"
echo "_Generated by AgentLife Life Ops — ${DATE}_" >> "$BRIEF_FILE"

echo "Daily brief saved: $BRIEF_FILE"
cat "$BRIEF_FILE"