#!/usr/bin/env bash
# Life Ops — Subscription Renewal Check
# Checks for upcoming subscription renewals and alerts
# Runs: daily at 8 AM

set -euo pipefail

DATA_DIR="${HOME}/.hermes/agentlife/data"
mkdir -p "$DATA_DIR"

ALERT_FILE="${DATA_DIR}/renewals-$(date +%Y-%m-%d).md"
LEAD_DAYS=14

cat > "$ALERT_FILE" << EOF
# 🔔 Subscription Renewal Check
## $(date "+%B %d, %Y")

**Alert Lead:** ${LEAD_DAYS} days

### Renewing Within ${LEAD_DAYS} Days
| Service | Amount | Renewal Date | Days Left |
|---------|--------|-------------|-----------|
| — | — | — | — |

### Total Monthly Committed Spend: N/A

---
_Generated by AgentLife Life Ops_
EOF

echo "Renewal check: $ALERT_FILE"
cat "$ALERT_FILE"