#!/usr/bin/env bash
# Life Ops — Weekly Spending Digest
# Summarizes the week's transactions and spending by category
# Runs: Monday at 9 AM

set -euo pipefail

DATA_DIR="${HOME}/.hermes/agentlife/data"
mkdir -p "$DATA_DIR"

DIGEST_FILE="${DATA_DIR}/spending-digest-$(date +%Y-%m-%d).md"

cat > "$DIGEST_FILE" << EOF
# 💳 Weekly Spending Digest
## Week of $(date "+%B %d, %Y")

**Total Spent:** N/A (configure expense tracking)

### By Category
| Category | Amount |
|----------|--------|
| — | — |

### Budget Check
| Category | Budget | Actual | Status |
|----------|--------|--------|--------|
| — | — | — | — |

---
_Generated by AgentLife Life Ops_
EOF

echo "Spending digest: $DIGEST_FILE"
cat "$DIGEST_FILE"